name: Greetings

on: [push]

jobs:
  greeting:
    runs-on: codebuild-ghactions-${{ github.run_id }}-${{ github.run_attempt }}
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: super-linter/super-linter@v5.7.2
